# Configuration
markdown: kramdown
sass:
  style: compressed
exclude:
  - .gitignore
  - README.md
  - Gemfile
  - Gemfile.lock

# Variables
title: Lukáš Kubánek - personal website
email: lukas.kubanek@me.com
twitter: kubanekl
github: lukaskubanek
