# Jekyll Configuration
markdown: kramdown
sass:
  style: compressed
exclude:
  - .gitignore
  - README.md
  - Gemfile
  - Gemfile.lock  

# Variables: Configuration
google_analytics_id: UA-35412582-1

# Variables: Content
title: Lukáš Kubánek - personal website
name: Lukáš Kubánek
email:
  link: lukas&#046;kubanek&#064;me&#046;com
  text: lukas&#046;<!---->kubanek<!---->&#064;me&#046;com
twitter: kubanekl
github: lukaskubanek
copyright: 
  content:
    name: Lukáš Kubánek
  photos:
    name: Marko Müller
    link: http://www.dermarko.de
