# Configuration
markdown: kramdown
sass:
  style: compressed
exclude:
  - .gitignore
  - README.md
  - Gemfile
  - Gemfile.lock

# Variables
title: Lukáš Kubánek - personal website
email: lukas.kubanek@me.com
twitter: kubanekl
github: lukaskubanek
copyright: 
  content:
    name: Lukáš Kubánek
  photos:
    name: Marko Müller
    link: http://www.dermarko.de
